#pom项目版本
version: @project.version@
spring:
  application:
    name: admin-client
  boot:
    admin:
      client:
        url: http://localhost:9010
server:
  port: 8769

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
